{% set name = "dandi" %}
{% set version = "0.58.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1287162192b60ea366f5916548b8e8760da65e564dc48107436b3cd92402f7bd

build:
  number: 0
  skip: true  # [py<38]
  entry_points:
    - dandi=dandi.cli.command:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - appdirs
    - bidsschematools >=0.7.0,<0.8.0
    - click
    - click-didyoumean
    - dandischema >=0.8.0,<0.9.0
    - etelemetry >=0.2.0
    - fasteners
    - fscacher
    - humanize
    - interleave
    - joblib
    - keyring !=23.9.0
    - keyrings.alt
    - nwbinspector >=0.4.28
    - packaging
    - pycryptodomex
    - pydantic >=1.9.0
    - pynwb >=1.0.3,!=1.1.0
    - pyout >=0.5,!=0.6.0
    - python-dateutil
    - requests >=2.20,<3.0
    - ruamel.yaml >=0.15,<1
    - semantic_version
    - tenacity
    - zarr >=2.10,<3.0
    - zarr-checksum

test:
  requires:
    - anys
    - bash >=4.5  # [not win]
    - docker-compose  # [not win]
    - git
    - opencv
    - pytest
    - pytest-mock
    - pytest-rerunfailures
    - responses !=0.24.0
    - vcrpy
  imports:
    - dandi
  commands:
    - python -m pytest -s -v -k "not test_validate_bogus" --pyargs dandi

about:
  home: https://github.com/dandi/dandi-cli
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Command line client for interaction with DANDI Archive elements
  dev_url: https://github.com/dandi/dandi-cli

extra:
  recipe-maintainers:
    - yarikoptic
    - jwodder
